#!/usr/bin/env python3
"""
SecureByte Society — CTF Platform
build.py  —  Converts challenges.json → js/challenges.js

Run this any time you edit challenges.json:
    python3 build.py

Also converts any file in assets/files/ into
a base64 entry in js/files.js automatically.
"""

import json, base64, pathlib, sys, os

ROOT = pathlib.Path(__file__).parent

def build_challenges():
    src  = ROOT / 'challenges.json'
    dest = ROOT / 'js' / 'challenges.js'

    if not src.exists():
        print(f'ERROR: {src} not found'); sys.exit(1)

    data = json.loads(src.read_text(encoding='utf-8'))
    count = len(data.get('challenges', []))

    js  = '/* ══════════════════════════════════════════════════════\n'
    js += '   SecureByte Society — CTF Platform\n'
    js += '   js/challenges.js  —  Auto-generated from challenges.json\n'
    js += '   DO NOT edit this file directly — edit challenges.json\n'
    js += '   then run:  python3 build.py\n'
    js += '   ══════════════════════════════════════════════════════ */\n\n'
    js += 'const SBS_DATA = '
    js += json.dumps(data, indent=2, ensure_ascii=False)
    js += ';\n'

    dest.write_text(js, encoding='utf-8')
    print(f'✅  challenges.js written — {count} challenge(s)')

def build_files():
    files_dir = ROOT / 'assets' / 'files'
    dest      = ROOT / 'js' / 'files.js'

    if not files_dir.exists():
        print(f'⚠   assets/files/ not found — skipping files.js update')
        return

    MIME = {
        '.txt':  'text/plain',
        '.html': 'text/html',
        '.htm':  'text/html',
        '.jpg':  'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.png':  'image/png',
        '.gif':  'image/gif',
        '.zip':  'application/zip',
        '.bin':  'application/octet-stream',
        '.pdf':  'application/pdf',
        '.py':   'text/plain',
        '.c':    'text/plain',
        '.sh':   'text/plain',
    }

    entries = []
    skipped = []
    for f in sorted(files_dir.iterdir()):
        if f.is_file() and not f.name.startswith('.'):
            try:
                b64  = base64.b64encode(f.read_bytes()).decode()
                mime = MIME.get(f.suffix.lower(), 'application/octet-stream')
                entries.append(f'  {json.dumps(f.name)}: {{ b64: {json.dumps(b64)}, mime: {json.dumps(mime)} }}')
                print(f'  + {f.name} ({f.stat().st_size} bytes)')
            except Exception as e:
                skipped.append(f.name)
                print(f'  ⚠ Skipped {f.name}: {e}')

    js  = '/* ══════════════════════════════════════════════════════\n'
    js += '   SecureByte Society — CTF Platform\n'
    js += '   js/files.js  —  Auto-generated from assets/files/\n'
    js += '   DO NOT edit this file directly\n'
    js += '   Run:  python3 build.py  to regenerate\n'
    js += '   ══════════════════════════════════════════════════════ */\n\n'
    js += 'const FILE_DATA = {\n'
    js += ',\n'.join(entries)
    js += '\n};\n'

    dest.write_text(js, encoding='utf-8')
    print(f'✅  files.js written — {len(entries)} file(s) embedded')
    if skipped:
        print(f'⚠   Skipped: {", ".join(skipped)}')

if __name__ == '__main__':
    print('SecureByte Society — Build Script')
    print('══════════════════════════════════')
    build_challenges()
    print()
    print('Embedding files from assets/files/:')
    build_files()
    print()
    print('Done! Open index.html in your browser.')
